#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: HUC-LUMS training Lahore 2023
author: OGGM Consortium  # The author of the book
copyright: "2023"  # Copyright year to be placed in the footer
logo: img/logo.png  # A path to the book logo

repository:
  url: https://github.com/OGGM/training-lahore
  path_to_book: docs 
  branch: main
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  google_analytics_id: UA-106829797-2
  extra_footer: |
    <p>
    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">
      <img align="right" class="margin" src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg" width="88px">
    </a>
    This work is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">Creative Commons Attribution 4.0 International (CC BY 4.0) license</a> unless specified otherwise.
    <br>
    &copy; Copyright OGGM Consortium 2022-2023.
    </p>
sphinx:
  config:
    html_show_copyright: false
execute:
  execute_notebooks: auto
  allow_errors: true
  timeout: -1
exclude_patterns: [.virtual_documents/*]
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
    